"""Add Vacancy, Application, Notification models

Revision ID: 4574cf78c46d
Revises: 5db7c830ea4e
Create Date: 2025-11-05 11:02:24.642879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4574cf78c46d'
down_revision: Union[str, None] = '5db7c830ea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
