"""add full_name to users

Revision ID: dcc18839c3b2
Revises: 5b08bf447c19
Create Date: 2026-04-23 10:31:08.480297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc18839c3b2'
down_revision: Union[str, None] = '5b08bf447c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('pipeline_stage', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('match_summary', sa.Text(), nullable=True))
    op.create_index('ix_applications_pipeline_stage', 'applications', ['pipeline_stage'], unique=False)
    op.create_index('ix_applications_rating', 'applications', ['rating'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_index('ix_applications_rating', table_name='applications')
    op.drop_index('ix_applications_pipeline_stage', table_name='applications')
    op.drop_column('applications', 'match_summary')
    op.drop_column('applications', 'pipeline_stage')
    op.drop_column('applications', 'rating')
    # ### end Alembic commands ###
