"""add resume parse

Revision ID: f0bb9038588a
Revises: 6ff0d6b22419
Create Date: 2026-04-23 12:16:24.099383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bb9038588a'
down_revision: Union[str, None] = '6ff0d6b22419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_path', sa.String(length=500), nullable=True),
    sa.Column('source_resume_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('normalized_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_resumes_user_id'), 'parsed_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_resumes_user_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    # ### end Alembic commands ###
